### ISSUE TITLE
Stored XSS в комментариях

### ISSUE THREAD

**Issue by FoggyX** [Mrak790/OurNFT#32]
Актуальный релиз не запускается на linux, там используется библиотека для windows, уязвимость можно воспроизвести на коммите 17cd95f9493081832a6713749ef147478ca294b9 (в более новых коммитах изменений, связанных с этой уязвимостью, замечено не было)
1. Регистрируемся в сервисе и логинимся
2. Загружаем любую публичную картинку
3. Переходим на страницу это картинки, отправляем любой комментарий и перехватываем запрос, подменяем значение параметра `content` на `<script>alert(1)</script>` 
4. Теперь на странице с комментариями к данной картинке выполняется `alert(1)`
![image](https://user-images.githubusercontent.com/50872838/162730812-b25e90ac-fe91-427f-bfd1-ce9b12747622.png)

CVSS: https://www.first.org/cvss/calculator/3.1#CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:L/RL:U

**Comment by OddMood** [comment]
Fixed in merge-request #33
